# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
     desc "Prep Amazon Appstore submission"
     lane :prep_amazon do
        amazon_app_submission(
            client_id: ENV["AMAZON_APPSTORE_CLIENT_ID"],
            client_secret: ENV["AMAZON_APPSTORE_CLIENT_SECRET"],
            app_id: ENV["AMAZON_APPSTORE_APP_ID"],
            apk_path: "app/build/outputs/apk/prod/release/app-prod-release.apk",
            upload_apk: true,
            upload_changelogs: false,
            submit_for_review: false
          )
     end

     desc "Submit to Amazon Appstore"
     lane :submit_amazon do
        amazon_app_submission(
            client_id: ENV["AMAZON_APPSTORE_CLIENT_ID"],
            client_secret: ENV["AMAZON_APPSTORE_CLIENT_SECRET"],
            app_id: ENV["AMAZON_APPSTORE_APP_ID"],
            submit_for_review: true
          )
     end
end
