name: KMP Build android app

on:
  workflow_dispatch:
    inputs:
      android_package_name:
        description: 'Name of the Android project module'
        type: string
        required: true
        default: 'app'
      build_type:
        description: 'Type of build to perform'
        type: string
        required: false
        default: 'Release'

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Android App
        uses: openMF/kmp-build-android-app-action@v1.0.0
        id: build-android
        with:
          android_package_name: ${{ inputs.android_package_name }}
          build_type: ${{ inputs.build_type }}
          google_services: ${{ secrets.GOOGLESERVICES_EN }}
          key_store: ${{ secrets.ORIGINAL_KEYSTORE_FILE }}
          key_store_password: ${{ secrets.ORIGINAL_KEYSTORE_FILE_PASSWORD }}
          key_store_alias: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS }}
          key_store_alias_password: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS_PASSWORD }}